## 4. Údržba a výměna řetězu

Řetěz je nejnamáhanější částí kola, a proto je mu potřeba věnovat dostatečnou péči. Důležitá je také jeho kontrola a včasná výměna. Pokud řetěz nevyměníme včas, zvyšujeme riziko nadměrného opotřebení ozubených kol pastorku a věnců převodníku, které pak musíme vyměnit za nové, což je značná investice oproti nákupu nového řetězu, který stojí pouze kolem 400 Kč. Někdo uvádí doporučení vyměnit řetěz asi po 3000 km. Já raději spoléhám na proměření řetězu pomocí speciálního kalibru, který lze zakoupit v každé cykloprodejně. Měření s ním je snadné a jednoduše poznáme, kdy je řetěz protažený nad přípustnou mez.

Co se týče mazání, raději volím řidší oleje jako je GT 85, které nepřitahují mnoho nečistot, i když se mohou v dešti rychleji vyplavit. Pokud je na řetězu nános špíny, je nejprve potřeba ji před mazáním odstranit. Dobrým pomocníkem je tzv. pračka řetězu, která se naplní rozpouštědlem jako je technický benzín, pak se nasadí na řetěz a zpětným otáčením pedálů dojde k očištění řetězu mezi otáčejícími se kartáčky. Nemáme-li pračku řetězu, použijeme obyčejný hadr a můžeme ještě řetěz postříkat čistícím prostředkem na kola, například já používám Cyklo Star.

Jednou za čas je dobré trochu pozornosti věnovat i pastorkům a převodníkům, jelikož ty se časem zanáší špínou slepenou s olejem ze řetězu. Nejlepší je použít starý hadr, který zasuneme do mezer mezi jednotlivá ozubená kola. Dá se také sehnat čistič pastorku, např. od firmy Vella. Pro lepší očištění také někdy používám starý zubní kartáček.

Velmi často jsem se setkal s tím, že mnoho lidí neví, jak a kde řetěz správně namazat. Správně namazaný řetěz musí být na povrchu zcela čistý a olej musí zůstat uvnitř řetězu, kde jsou jeho funkční plochy. Proto jej po namazání nezapomeňte zvenku otřít. Nebude se vám pak na něj lepit prach a vy zůstanete čistí.

K výměně řetězu je u dnešních kol nezbytné použít nýtovač řetězu. Při rozpojování je důležité nýt úplně nevytlačit ze spojky, protože už ho není možné dát zpátky. Po spojení řetězu je zase dobré ho rozhýbat v místě spoje a již ho v tomto místě nikdy znovu nerozpojovat, neboť hrozí jeho samovolné rozpojení. Pokud máte na kole řetěz Shimano IG nebo HG, tak ty se spojují speciálními nýty, které mají zúžený začátek, což ulehčuje zavedení nýtu do spojky a poté se odlomí. Nýtovač se používá stejný jako v případě jiných řetězů.

## 6. Jak namazat bowdeny řazení

Po delším čase se nám může stát, že nejde řadit tak hladce jako dříve. Je to většinou způsobeno tím, že se lanka a bowdeny zanesou nečistotami. Bowdeny je možné jednoduchým způsobem uvolnit a posunout po lanku bez povolování upevňovacích šroubů na přehazovačce nebo přesmykači. Pro uvolnění bowdenu u přehazovačky si zařadíme tak, aby se řetěz nacházel na největším pastorku. Tím se lanko napne a my bez otáčení zadního kola přeřadíme páčkou nebo otočnou rukojetí na nejmenší pastorek. Poté je už snadné bowden vyndat z úchytů a dané místo lanka namazat olejem na jízdní kola. Po namazání bowden vsuneme zpět do úchytů a páčkou přeřadíme zpět na největší pastorek. Podobně postupujeme při mazání lanka pod bowdenem u přesmykače, a to tak, že zařadíme na největší převodník a opět bez otáčení kola páčku (rukojeť) přesuneme do pozice pro zařazení nejmenšího převodníku.
